name: Build for Develop pre-release

on:
  push:
    branches:
      - !main

jobs:
  build-develop:
    name: Build Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: npm version "$(BRANCH=${GITHUB_REF_NAME} node scripts/npm-version.cjs)" --no-git-tag-version

      - name: Build lib for NPM
        run: npm run build

      - name: Run Orion post build script
        run: node scripts/ci-build-lib.cjs

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
