name: Build documentation for pre-release

on:
  release:
    types: [published]

jobs:
  build-publish-production:
    name: Build Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build lib
        run: npm run build

      - name: Run post build script
        run: node scripts/ci-build-lib.cjs
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: orion-build

  build-doc-production:
    name: Build Doc
    runs-on: ubuntu-latest
    needs: build-publish-production
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download lib build result
          uses: actions/download-artifact@v3
          with:
            name: orion-build

      - name: Build doc
        run: npm run docs:build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vuepress/dist

      - name: Deploy artifact
        uses: actions/deploy-pages@v2
