name: Build Pull Request

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'assets/**'
      - 'devtool/**'
      - 'lang/**'
      - 'lib/**'
      - 'packages/*/src/**'
      - 'packages/*/index.ts'
      - 'scripts/**'
      - 'services/**'
      - 'utils/**'
      - 'cli.cjs'
      - 'vite.config.ts'
      - '**.yml'

jobs:
  build-lib:
    uses: ./.github/workflows/build-lib.yml
