name: Build & Publish for production

on:
  release:
    types: [published]

jobs:
  build-lib:
    uses: ./.github/workflows/build-lib.yml

  publish-production:
    name: Build & Publish to NPM
    runs-on: ubuntu-latest
    need: build-lib
    steps:
      - name: Bump version
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Publish to NPM for production
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
